### ISSUE TITLE
Consider embedding "make" functionality entirely inside hl script

### ISSUE THREAD

**Issue by jrk** [alexreinking/halide-project-tool#8]

**Comment by alexreinking** [comment]
There are a few pros and cons to this:

Pros:

1) Separating `hl` from any particular build system allows it to be integrated cleanly into any other build system.
2) Removing an external dependency always alleviates compatibility issues and makes deployment clearer. The various make versions in the wild (including macOS's ancient 3.81) have already caused headaches.

Cons:

1) Currently, `hl` uses a variable naming convention in the Makefiles to support multiple generator configurations. An alternative format (yml? json?) would need to be introduced.
2) It would greatly complicate `hl`'s code and require replicating a significant amount of build knowledge in it. For instance, implementing incremental builds is complex (and necessary to keep Pro #2).

I'm hesitant to introduce any dependency that isn't already abundantly standard or readily available in the Debian stable / Ubuntu repos.

**Comment by jrk** [comment]
## Con 1
Saved configurations in a standard serialization seem the most straightforward. I also wonder how much might be achievable with simple conventions and introspection on the raw source. This won't cover everything, but maybe there's a way to still cover a lot with no config files at all?

## Con 2
I don't think incremental builds need to be built into `hl`, necessarily. Another design point would be to simply view it as a compiler driver program. It could be used as a build tool by any higher-level build automation, which would itself manage incremental artifact creation and updates. Think `gcc` (which wraps `cc`, `as`, `ld`, `ar`, etc., depending on the exact command and arguments run) more than `make`.

There are certainly tradeoffs with different design approaches. Integrating and automating more functionality in a fully self-contained way provides an easier and more streamlined path for new users and quick one-offs. My intuition, though, is that mirroring standard build tools, and focusing on _simple_ (relatively singular, decomposed, easy-to-understand-and-integrate tasks and roles) rather than _easy_ (requiring the fewest user actions to achieve common results), is the right starting point.

**Comment by alexreinking** [comment]
> Saved configurations in a standard serialization seem the most straightforward. I also wonder how much might be achievable with simple conventions and introspection on the raw source. This won't cover everything, but maybe there's a way to still cover a lot with no config files at all?

Maybe by adding structured comments to the source or by otherwise extending Halide Generators to have named configurations (this seems promising). There's no good way to set combinations of GeneratorParams at the moment.

> Another design point would be to simply view it as a compiler driver program. It could be used as a build tool by any higher-level build automation, which would itself manage incremental artifact creation and updates. Think `gcc` (which wraps `cc`, `as`, `ld`, `ar`, etc., depending on the exact command and arguments run) more than `make`.

That doesn't handle the project and generator-source generation ("generator ... generation" ugh) stories, though. The `hl` tool could create default project files (either make or cmake) which use itself as a compiler wrapper.

Still, it's tricky to get end-to-end behavior right. If you create one generator binary (which improves build performance), then you need to know that you only need to call the generator binary on the generators that were touched, not all of them. The current Makefile is smart enough to do this, and it is correct as long as you keep to one generator per source file. The main issue is that we don't go straight from Halide source to object files or libraries (static or shared), but we have this intermediate step that can incorporate 3rd party libraries and the like.

If we create separate generator binaries for every generator class, then we're going to spend a lot longer linking the same binaries and spitting intermediate binaries everywhere. But maybe that's tolerable?

**Comment by alexreinking** [comment]
After talking about this offline, we concluded that `hl` should impose one very basic convention and rely on **generator aliases** instead of the existing generator configs setup. It should provide tools for wrapping a supported compiler (gcc, clang, msvc) to help create every kind of object in a Halide library.

# Convention

Each generator class shall be defined in exactly **one** source file named "GENERATOR.gen.cpp" where "GENERATOR" is the name of the generator. This source file shall contain exactly the set of `HALIDE_REGISTER_GENERATOR` and `HALIDE_REGISTER_GENERATOR_ALIAS` pertinent to GENERATOR

The `hl` tool will occasionally call a system compiler. It first looks for `HLCC`, `HLCXX`, and `HLLD` in the environment and falls back to `CC`, `CXX`, and `LD` if those are not available. If no environment variable is present, `hl` will attempt to detect which compiler was used to build the Halide present in `HALIDE_DISTRIB_PATH` and use that one (or a compatible one) if available.

## Detecting compilers

A note to myself for later:
```
[alex@reinking-arch Halide]$ readelf -p .comment ${HALIDE_DISTRIB_PATH}/bin/libHalide.so

String dump of section '.comment':
  [     0]  GCC: (GNU) 8.3.0
  [    11]  GCC: (GNU) 8.2.1 20181127

[alex@reinking-arch Halide]$ gcc -dumpfullversion -dumpversion
9.1.0
```

Part 11 seems to be the relevant bit in an ELF-formatted binary. Will need to see how it works on macOS (Mach-O) and Windows (PE)

# Compile outputs

There are several passes that happen when building a library of Halide pipelines:

* `A.gen.cpp` -> `A.gen.o` -- Create the object file for compiling the generator
* `*.gen.o` -> `generator` -- Create the generator executable
* `generator` -> `A.o` -- Create the pipeline object
* `generator` -> `runtime.o` -- Get a compatible runtime for all generators
* `*.o` + `runtime.o` -> `library.{so,dylib,dll,a,lib}` -- Build the final artifact from all the generators.

The `A.o` files don't depend on `generator` directly, but on their associated `A.gen.o` / `A.gen.cpp` files. Their dependence on `generator` is order-only (from Make's perspective).

The final `library.so` (etc.) can be used to quickly produce a RunGenMain runner / benchmarker.

# Todo

* How to work with generator stubs?
